CONTRIBUTING.md
Fixes the need to add contributing.md to this repo.
=> Contributing.md needs to be updated

CONTRIBUTING.md
resolves #5
As per #5, I've made some improvements to CONTRIBUTING.md. In detail, I added some headings and bulleted lists, inserted links to relevant material, and revised the phrasing.
=> Re: Format contributing.md to make it look more professional

Bug Bounty Notes/Introduction.md
Edited the Bug Bounty Notes file to conform to markdown to make it a bit more professional and readable
=> Edited Bug Bounty Notes Introduction

Bug Bounty Notes/SQL Injection/sqlinjection.md
=> add tutorials for sql injection

Bug Bounty Notes/SSRF/ssrf.md
=> added ssrf tutorials

Linux Privilege Escalation Notes/Escalation Paths/Kernel Exploits/Kernel Exploits.md
=> added a list of tutorials to Linux Kernel Exploits

Linux Privilege Escalation Notes/Escalation Paths/Sudo/Sudo.md
=> added tutorials for Linux Sudo Privilege Escalation

Linux Privilege Escalation Notes/Escalation Paths/SUID/SUID.md
=> added tutorials for SUID

Linux Privilege Escalation Notes/Linux Enumeration/System Enumeration/System Enumeration.md
=> added tools to linux system enumeration

Linux Privilege Escalation Notes/Linux Enumeration/System Enumeration/System Enumeration.md
=> added tutorials to Linux System Enumeration

Windows Privilege Escalation Notes/Escalation Paths/Kernel Exploits/Kernel Exploits.md
=> added extensive notes and links to tools for Windows Kernel Exploits

Windows Privilege Escalation Notes/Escalation Paths/DLL Hijacking/DLL Hijacking.md
=> Added DLL Hijacking Tools

Windows Privilege Escalation Notes/Escalation Paths/Registry Escalation Path/Registry Escalation Path.md, Windows Privilege Escalation Notes/Initial Enumeration/AV and Firewall Enumeration/AV and Firewall Enumeration.md, Windows Privilege Escalation Notes/Initial Enumeration/Network Enumeration/Network Enumeration.md, Windows Privilege Escalation Notes/Initial Enumeration/Password Hunting/password hunting.md, Windows Privilege Escalation Notes/Initial Enumeration/System Enumeration/Windows System Enumeration.md, Windows Privilege Escalation Notes/Initial Enumeration/User Enumeration/User Enumeration.md, Windows Privilege Escalation Notes/Introduction.md
Not connected to any open issue but just something I noticed that needed doing.
=> made many minor but important edits

Windows Privilege Escalation Notes/Escalation Paths/RunAs/RunAs.md
=> Added RunAs Notes

Windows Privilege Escalation Notes/Escalation Paths/Registry Escalation Path/Registry Escalation Path.md
=> added registry escalation tools

Bug Bounty Notes/Code Injection/codeinjection.md, Windows Privilege Escalation Notes/Escalation Paths/Executable Files.md/Executable Files.md, Windows Privilege Escalation Notes/Escalation Paths/Executable Files/Executable Files.md, Windows Privilege Escalation Notes/Escalation Paths/Kernel Exploits/Kernel Exploits.md, Windows Privilege Escalation Notes/Escalation Paths/Passwords and Port Forwarding/passwords and port forwarding.md, Windows Privilege Escalation Notes/Escalation Paths/Service Permissions/Service Permissions.md
Closes #56 
Closes #71 
Closes #72 
Closes #76 
Closes #84
=> closing a lot of open issues

Linux Privilege Escalation Notes/Using Automated Tools/LinEnum.md, OSINT/Google Dorking/googledork.md, OSINT/Introduction.md, Tools/Jack The Ripper/jacktheripper.md, Tools/MetaSploit/MetaSploit.md, Tools/Nmap/nmap.md, Tools/Wireshark/wireshark.md, Tools/sqlmap/sqlmap.md, Windows Privilege Escalation Notes/Exploring Automated Tools/powerup/powerup.md
Closes #99 
Closes #98 
Closes #97 
Closes #96 
Closes #95 
Closes #94 
Closes #93
=> add more tools to the notes

OSINT/Email OSINT/emailosint.md, OSINT/Facebook OSINT/facebookosint.md, OSINT/Github OSINT/githubosint.md, OSINT/Image OSINT/imageosint.md, OSINT/Password OSINT/passwordosint.md, OSINT/Phone OSINT/phoneosint.md, OSINT/Reddit OSINT/redditosint.md, OSINT/SnapChat OSINT/snapchatosint.md, OSINT/TikTok OSINT/tiktokosint.md, OSINT/Twitter OSINT/twitterosint.md
This is just mostly section headings with more content to come later
=> Add more to the OSINT Section

OSINT/Email OSINT/emailosint.md, Tools/Burp Suite/burpsuite.md, Tools/OWASP ZAP/owaspzap.md, Windows Privilege Escalation Notes/Exploring Automated Tools/Watson/watson.md, Windows Privilege Escalation Notes/Exploring Automated Tools/jaws-enum/jaws-enum.md, Windows Privilege Escalation Notes/Exploring Automated Tools/sherlock/sherlock.md, Windows Privilege Escalation Notes/Exploring Automated Tools/winPEAS/winPEAS.md
Closes #107 
Closes #92
Closes #101
Closes #102 
Closes #103 
Closes #104
=> add more notes to various tools

OSINT/Email OSINT/emailosint.md, OSINT/Facebook OSINT/facebookosint.md, OSINT/Github OSINT/githubosint.md, OSINT/Image OSINT/imageosint.md, OSINT/Password OSINT/passwordosint.md, OSINT/Reddit OSINT/redditosint.md, OSINT/SnapChat OSINT/snapchatosint.md, OSINT/TikTok OSINT/tiktokosint.md
Closes #119 
Closes #118 
Closes #117 
Closes #116 
Closes #115 
Closes #114 
Closes #113 
Closes #112
=> added more extensive notes to the majority of the OSINT section

Bug Bounty Notes/SQL Injection/sqlinjection.md, OSINT/Image OSINT/imageosint.md, OSINT/Phone OSINT/phoneosint.md, OSINT/Twitter OSINT/twitterosint.md, Report Outlines/OSCP Scripts/OSCP Scripts.md, Report Outlines/OSCP Scripts/generate_report.sh, Report Outlines/OSCP Scripts/makesubmissions.sh, Tools/Jack The Ripper/jacktheripper.md, Tools/MetaSploit/MetaSploit.md, Windows Privilege Escalation Notes/Escalation Paths/Esclation Paths.md
Closes #122 
Closes #121 
Closes #128 
This PR closes three issues but also fixes many minor issues. Some of the issues are incomplete but in progress, so they aren't closed yet.
=> updated many things

Bug Bounty Notes/Race Condition/racecondition.md, Bug Bounty Notes/SQL Injection/sqlinjection.md, Bug Bounty Notes/XXE Injection/xxeinjection.md, Linux Privilege Escalation Notes/Escalation Paths/Passwords and File Permissions/Passwords and File Permissions.md
Closes #127 
Closes #126 
Close #125 
Closes #124
=> closing the opened tickets

Linux Privilege Escalation Notes/Linux Enumeration/Password Hunting/password-cracking.md, Windows Privilege Escalation Notes/Exploring Automated Tools/Sharup/Sharup.md
=> just adding some elements so I can close some open tickets

HTB-Walkthroughs/Jerry/Jerry-walkthrough.md, HTB-Walkthroughs/introduction.md
htb walkthroughs are still a work in progress. Right now I am just adding the framework for the walkthroughs I am going to add in the future.
=> added more to the htb walkthroughs

HTB-Walkthroughs/OSCP-Prep.md
Added more to the OSCP prep. Of  course, I will need to add walkthroughs for all of these boxes in order to create a more comprehensive study guide.
=> added more to the htb boxes needed for OSCP prep

README.md
Hopefully, this is one of the last changes I will need to make in a while.
=> made more updates to the table of contents

Windows-Privilege-Escalation/Escalation Paths/Avtive Ditrctory/GoldenTicketAttack.md, Windows-Privilege-Escalation/Escalation Paths/Avtive Ditrctory/PrivExchangeAttack.md
Closes #154 
This PR would close the above ticket and as such adds more to the repository about all the ways to attack an Active Directory network.
This is key knowledge to know when actually working as a penetration tester as AD networks will be the most common encountered.
=> added more to the esclation paths for active directory

HTB-Walkthroughs/Active-Directory-Focused.md
=> added more to the active directory boxes on hackthebox

Bug-Bounty/Business Logic/businesslogic.md, Bug-Bounty/ClickJacking/clickjacking.md, Bug-Bounty/Cross Origin Resource Sharing/CORS.md, Bug-Bounty/DOM Based Vulnerabilities/DOM-Based.md, Bug-Bounty/JWT Attacks/jwt-attacks.md, Bug-Bounty/OAuth2 Authentication Vulnerabilities/OAuth.md, Bug-Bounty/Web Cache Poisoning/WebCache.md, Bug-Bounty/XXE Injection/xxeinjection.md, checklists/introduction.md
Added a bunch of blank (to be filled) bugs in bug bounty.
=> added more types of bugs in bug bounty

Bug-Bounty/AWS Amazon Bucket S3/AWSBucket.md
=> added an explaination to Amazon S3 Buckets

Bug-Bounty/CSV Injection/CSVInjection.md
Closed #182 
Closed #183 
Closed #184 
This pull request closes all three tickets above.
=> added CSV Injection to bug bounty

Bug-Bounty/API Key Leaks/apikey.md
Closed #195 
Closed #199 
This pull request closes the above mentioned tickets.
=> Added Tutorials and Payloads for API Keys

Bug-Bounty/Cross Origin Resource Sharing/CORS.md
Closed #197 
Closed #185 
This pull request closes the two tickets mentioned above.
=> Added payloads and tutorials to CORS

Bug-Bounty/JWT Attacks/jwt-attacks.md, Bug-Bounty/Web Cache Poisoning/WebCache.md, Bug-Bounty/XPATH Injection/xpath.md, Bug-Bounty/XSLT Injection/xslt.md
=> added a bunch to bug bounty

Bug-Bounty/XPATH Injection/xpath.md, Bug-Bounty/XSLT Injection/xslt.md, Bug-Bounty/XXE Injection/xxeinjection.md
Closed #231 
Closed #229 
Closed #226
=> added tutorials to a couple of sections

Bug-Bounty/DOM Based Vulnerabilities/DOM-Based.md, Bug-Bounty/NoSQL Injection/nosql.md, Bug-Bounty/Web Cache Poisoning/WebCache.md, Bug-Bounty/XPATH Injection/xpath.md
Closed #230 
Closed #222 
Closed #214 
Closed #211 
This PR closes the above 4 tickets.
=> added more to the bug bounty section including payloads

Bug-Bounty/DOM Based Vulnerabilities/DOM-Based.md, Bug-Bounty/Directory Transversal/directory.md, Bug-Bounty/XSLT Injection/xslt.md
Closed #227
Closed #210 
Closed #209 
Closed #208 
This PR closes the above mentioned tickets.
=> added even more to the bug bounty section

Bug-Bounty/XXE Injection/xxeinjection.md, Tools/CMSMap/CMSMap.md
=> added xxe injection payloads

Bug-Bounty/Argument Injection/argument.md
=> added payloads to argument injection to close 188

Tools/WPScan/WPScan.md
=> added a tutorial for wpscan

Tools/Fierce/fierce.md
=> added a tutorial or a least a start of a tutorial to the fierce tool

Tools/Kismet-Wireless/kismet-wireless.md
=> added more to the Kismet-wireless tutorial

Tools/Skipfish/skipfish.md
=> added a tutorial on skipfish

Tools/merlin/merlin.md
=> added a tutorial for merlin

Tools/Netcat/netcat.md
=> added a tutorial for netcat

Tools/OpenVAS/openvas.md
=> added a tutorial for openvas

Tools/Dirb/dirb.md
=> added a tutorial for dirb

Tools/Hydra/hydra.md
=> added a tutorial on hydra

Tools/Apktool/apktool.md
=> added a tutorial on the apktool

Tools/Tiger/Tiger.md
=> added Tiger to the tools section

Tools/Reaver/reaver.md
=> added a tutorial on reaver

Tools/Maltego/maltego.md
=> added the Maltego tool to the repo

Tools/Yersinia/Yersinia.md
=> added a tutorial for yersimia

Tools/Lynis/lynis.md
=> added a tutorial for Lynis

Tools/ffuf/ffuf.md
=> added a tutorial on ffuf

Tools/smbclient/smbclient.md
=> added smbclient to the tools

Tools/crackmapexec/crackmapexec.md
=> added a tutorial on crackmapexec

Tools/King Phisher/king-phisher.md
=> added a tutorial on king phisher

Tools/gobuster/gobuster.md
=> added gobuster to the list of tools

Tools/NTLMRelay/ntlmrelay.md
=> added ntlmrelay to the tools

Tools/Inveigh/inveigh.md
=> added inveigh to the tools section

Tools/Responder/responder.md
=> added responder to the repository

Tools/linux-exploit-suggester/linux-exploit-suggester.md
=> added linux exploit suggester to the tools

Tools/Splunk/splunk.md
=> added splunk to the tools

Tools/ELK Stack/elkstack.md
=> added elkstack to the tools

Tools/Ettercap/Ettercap.md
=> added ettercap to the tools

Tools/pwncat-cs/pwncat-cs.md
=> added pwncat-cs to the tools

Tools/Introduction.md
=> updated the tools table of contents

Tools/amass/amass.md
=> added amass to the tools section

Tools/Nessus/Nessus.md
=> added Nessus to the tools section

Tools/Bettercap/bettercap.md
=> added bettercap to the tools section

Tools/Nishang/Nishang.md
=> added a tutorial on the Nishang tool

Tools/Covenant/covenant.md
=> added covenant tool to the repository

Tools/PowerSploit/powersploit.md
=> added powersploit to the notes

Tools/Powershell Empire/powershell-empire.md
=> added powershell empire

Tools/Empire/empire.md
=> added Empire to the list of tools

HTB-Walkthroughs/Machines/Windows Machines/easy/Eternal Blue/introduction.md
This is a rough draft of a walkthrough on Blue, more details and screenshots should be added later on.
=> created a draft walkthrough for Blue on HTB

Job-Interview-Prep/windows-focused.md
- Added more to the windows focused job interview questions
=> added more to the windows focused interview questions

Linux-Privilege-Escalation/Escalation Paths/Kernel Exploits/Kernel Exploits.md
- Updated the Kernel Exploits portion of the Linux Privilege Escalation 
- The update includes a more exhaustive explanation of the Linux kernel and its components.
=> updated the kernel exploits portion in Linux Priv Esc

Job-Interview-Prep/Non-technical-junior-role.md
- Added more answers to some junior level questions
=> Answered some more junior questions

Job-Interview-Prep/linux-focused.md
- Added more to the Linux focused questions specifically concerning logs and other error handling
=> added more to the linux focused questions

Job-Interview-Prep/Non-technical-senior-role.md
- Added more to the Non technical senior role interview questions
=> added more to the non technical senior role interview

CTF/VulnHub/VulnHub.md
- Added a section on CTF's for publishing breakthroughs at a later date.
=> added a ctf section for later walkthroughs

CTF/Building-VMs/building-vms.md
- A summary of how to build a vulnerable VM
- This is something I asked in the hacksmarter discord and was given a lot of resources that I found helpful
- This is a compilation of all of those resources in a succinct guide.
=> A summary of how to build a vulnerable VM
